version: 0.2

phases:
  build:
    commands:
      - echo "Nothing to build for static site"
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
